### PR TITLE
added favicon support

### PR DESCRIPTION
**Pull request by caarlos0**
Hey, great tool!

Not sure if desired or if its the best design, but I added a little thingy so if there is a `favicon.ico` file in the source dir, it copies it the destination dir and injects the favicon header tag :) 

Also fixed the injects test, seems like it was testing something in the up code(?), I assumed it was wrong due to some migration or whatever, let me know if you want it reverted 😄 

Cheers!

### CODE REVIEW

**Comment by tj** [comment]
I forget if I set it up this way, but ideally the theme isn't replaced on subsequent `static-docs` calls, then people can tweak the header however, especially since there's like 15 favicons for all those sizes hahah. 

We could maybe just add the standard link tag since the browser requests it anyway, not sure hmm

**Comment by tj** [comment]
oh I see we aren't copying everything into `build`, hmm haha. I suppose it works a bit better when `-out` is `.` so you can just have the other static files right there.

I guess the ./theme dir should be outside of the build too, I dunno hahah dirty hack for now :D

**Comment by caarlos0** [comment]
@tj dunno, haha, didn't test this scenario... I've seen that every file in `src` is expected to be a markdown file, so if I have any images there the page gets generated wrong... (with image bytes inlined etc)

**Comment by tj** [comment]
Yeah I need to think about it some more hahah.

I was thinking:

```
$ static-docs -in ./docs -out .
```

Would work fine since you'd get:

```
    ├── index.html
    └── theme
        └── apex
            ├── css
            │   └── index.css
            ├── js
            │   ├── index.js
            │   └── smoothscroll.js
            └── views
                └── index.html
```

but if it's `-out build` (default) then that's no good

**Comment by caarlos0** [comment]
FWIW, I get a branch that supports adding scripts and styles as well... had to use kingpin to accept slice flags and etc, I can open a pr if you like but it looks kind of ugly now -> https://github.com/caarlos0/static/tree/next

**Comment by tj** [comment]
I think we might be safer having a way for people to edit the theme views without the command overriding their changes, otherwise there's so many cases we'd probably have to cover.

**Comment by caarlos0** [comment]
Yeah that makes a lot of sense!  Let me know if I can help 🚀

**Pull request closed without merging**
