### PR TITLE
feat: support syntax-highlight via chroma

### LINKED ISSUE #26: Syntax highlighting
via https://github.com/alecthomas/chroma

### PR DESCRIPTION
**Pull request by caarlos0**
closes #26

hey @tj , I wanted this and also wanted to play with chroma so I went ahead and implemented it :) 

hope it is good 🍻 

looks like this:

image

thanks for the great tool btw 🍰

### CODE REVIEW

**Comment by tj** [comment]
Awesomee thanks man I'll check this out today and decide what I want to do for the default syntax theme

**Comment by caarlos0** [comment]
hey @tj, sorry to bother, but, did you got the change to take another look at this?

**Comment by tj** [comment]
pretty dope! Weird that they don't just attach classnames and let styling be in CSS, not sure how I feel about that part shame it can't be overridden in the theme easily, will hard-code some stuff for now! thanks man

**Comment by tj** [comment]
nvm it does have that hahah

**Comment by caarlos0** [comment]
yeaaaaaaaaahs =D

oh weee

**Pull request merged**
